scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test the CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml"
    # `olm` tests configured to test the CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml"
