apiVersion: v1
kind: Namespace
metadata:
  name: ibm-common-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-auditlogging-operator
  labels:
    app.kubernetes.io/instance: "common-audit-logging"
    app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
    app.kubernetes.io/name: "common-audit-logging"
spec:
  selector:
    matchLabels:
      name: ibm-auditlogging-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: ibm-auditlogging-operator
        app.kubernetes.io/instance: "common-audit-logging"
        app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
        app.kubernetes.io/name: "common-audit-logging"
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
        openshift.io/scc: restricted
    spec:
      serviceAccountName: ibm-auditlogging-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
      - name: ibm-auditlogging-operator
        command:
        - /manager
        args:
        - --enable-leader-election
        - --metrics-addr=:8383
        image: quay.io/opencloudio/ibm-auditlogging-operator:latest
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            value: ""
          # DO NOT DELETE. Add image SHAs here. See get_image_sha.sh
          - name: FLUENTD_TAG_OR_SHA
            value: sha256:bebccda15d44814ccabb21545673e9424b1c34449e8936182d8c1f416297b9a7
          - name: JOB_TAG_OR_SHA
            value: sha256:ba876b826155960f2523d14b191185b75956b6bf53b68c0fc76acd609f9e231f
          - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      - name: audit-policy-controller
        image: quay.io/opencloudio/audit-policy-controller@sha256:e505e7e3183fe6c54ce3ebe0e33e16d64a69e0a0cd04e8f8beaa255028f0ddb3
        imagePullPolicy: IfNotPresent
        args:
        - --v=0
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - pgrep audit-policy -l
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: [ "sh", "-c", "exec echo start audit-policy-controller" ]
          initialDelaySeconds: 10
          timeoutSeconds: 2
        resources:
          limits:
            memory: 400Mi
            cpu: 100m
          requests:
            memory: 150Mi
            cpu: 20m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
