apiVersion: v1
kind: Namespace
metadata:
  name: ibm-common-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-auditlogging-operator
  namespace: ibm-common-services
  labels:
    app.kubernetes.io/instance: "common-audit-logging"
    app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
    app.kubernetes.io/name: "common-audit-logging"
spec:
  selector:
    matchLabels:
      name: ibm-auditlogging-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: ibm-auditlogging-operator
        app.kubernetes.io/instance: "common-audit-logging"
        app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
        app.kubernetes.io/name: "common-audit-logging"
        intent: projected
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
        openshift.io/scc: restricted
    spec:
      serviceAccountName: ibm-auditlogging-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
      - name: ibm-auditlogging-operator
        command:
        - /manager
        args:
        - --enable-leader-election
        - --metrics-addr=:8383
        image: icr.io/cpopen/ibm-auditlogging-operator:3.21.0
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FLUENTD_IMAGE
            value: qicr.io/cpopen/cpfs/fluentd:v1.14.5-bedrock-3
          - name: AUDIT_GARBAGE_COLLECTOR_IMAGE
            value: icr.io/cpopen/cpfs/audit-garbage-collector:1.10.0
          - name: AUDIT_POLICY_CONTROLLER_IMAGE
            value: icr.io/cpopen/cpfs/audit-policy-controller:3.15.0
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
