apiVersion: v1
kind: Namespace
metadata:
  name: ibm-common-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-auditlogging-operator
  namespace: ibm-common-services
  labels:
    app.kubernetes.io/instance: "common-audit-logging"
    app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
    app.kubernetes.io/name: "common-audit-logging"
spec:
  selector:
    matchLabels:
      name: ibm-auditlogging-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: ibm-auditlogging-operator
        app.kubernetes.io/instance: "common-audit-logging"
        app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
        app.kubernetes.io/name: "common-audit-logging"
        intent: projected
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
        openshift.io/scc: restricted
    spec:
      serviceAccountName: ibm-auditlogging-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
      - name: ibm-auditlogging-operator
        command:
        - /manager
        args:
        - --enable-leader-election
        - --metrics-addr=:8383
        image: quay.io/opencloudio/ibm-auditlogging-operator:3.8.3
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FLUENTD_TAG_OR_SHA
            value: sha256:6295dcf81f28db8615be8599f95dbabd431939c4813b69a2998814b209b7e988
          - name: JOB_TAG_OR_SHA
            value: sha256:030c97accc7525f5064632e7f824661ec7be782a42f683e2d025c0a0d91bbb1a
          - name: POLICY_CTRL_TAG_OR_SHA
            value: sha256:3d920dbf95f9e14b95eecc72ce983165e19faf9b887d82386b94b11111df0b00
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
