apiVersion: v1
kind: Namespace
metadata:
  name: ibm-common-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-auditlogging-operator
  namespace: ibm-common-services
  labels:
    app.kubernetes.io/instance: "common-audit-logging"
    app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
    app.kubernetes.io/name: "common-audit-logging"
spec:
  selector:
    matchLabels:
      name: ibm-auditlogging-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: ibm-auditlogging-operator
        app.kubernetes.io/instance: "common-audit-logging"
        app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
        app.kubernetes.io/name: "common-audit-logging"
        intent: projected
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
        openshift.io/scc: restricted
    spec:
      serviceAccountName: ibm-auditlogging-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
      - name: ibm-auditlogging-operator
        command:
        - /manager
        args:
        - --enable-leader-election
        - --metrics-addr=:8383
        image: quay.io/opencloudio/ibm-auditlogging-operator:3.9.0
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FLUENTD_TAG_OR_SHA
            value: sha256:bf2940b2e7ab7c68c880185c7bc66775ac1e44d93bf24a83cb38b6413a1337de
          - name: JOB_TAG_OR_SHA
            value: sha256:f8d6b9fa47aaf904e034402e12fa9f06fdfc391974fdb3c1e28d2cc1a6a876b3
          - name: POLICY_CTRL_TAG_OR_SHA
            value: sha256:c00a648d229eadfaffaa4361652af63d749c8d80e62249f9520d75716ab0c452
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
