apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: common-audit-logging
    app.kubernetes.io/managed-by: ibm-auditlogging-operator
    app.kubernetes.io/name: common-audit-logging
  name: auditpolicies.audit.policies.ibm.com
spec:
  group: audit.policies.ibm.com
  names:
    kind: AuditPolicy
    plural: auditpolicies
    shortNames:
    - ap
  scope: Namespaced
  versions:
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterAuditPolicy:
                description: enforce, inform
                type: object
              labelSelector:
                description: selecting a list of namespaces where the policy applies
                type: object
              namespaceSelector:
                description: namespaces on which to run the policy
                properties:
                  exclude:
                    items:
                      type: string
                    type: array
                  include:
                    items:
                      type: string
                    type: array
                type: object
              remediationAction:
                description: remediate or enforce
                type: string
            type: object
          status:
            properties:
              auditDetails:
                description: selecting a list of services to validate
                type: object
              compliant:
                type: string
            type: object
  versions: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
