# permissions for end users to view auditloggings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auditlogging-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - auditloggings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - auditloggings/status
  verbs:
  - get
