# permissions for end users to edit commonaudits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonaudit-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - commonaudits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - commonaudits/status
  verbs:
  - get
