apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: common-audit-logging
    app.kubernetes.io/managed-by: ibm-auditlogging-operator
    app.kubernetes.io/name: common-audit-logging
  name: ibm-auditlogging-operator
rules:
  - apiGroups:
      - operator.ibm.com
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - audit.policies.ibm.com
    resources:
      - auditpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - audit.policies.ibm.com
    resources:
      - auditpolicies/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - certmanager.k8s.io
    resources:
      - clusterissuers
    verbs:
      - use
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: common-audit-logging
    app.kubernetes.io/managed-by: ibm-auditlogging-operator
    app.kubernetes.io/name: common-audit-logging
  name: ibm-auditlogging-operator
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - apps
    resourceNames:
      - ibm-auditlogging-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - certmanager.k8s.io
    resources:
      - certificates
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - restricted
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
