apiVersion: operator.ibm.com/v1
kind: CommonAuditLogging
metadata:
  name: example-commonauditlogging
  labels:
    app.kubernetes.io/instance: "common-audit-logging"     
    app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
    app.kubernetes.io/name: "common-audit-logging"
spec:
  enabled: true
  imageRegistry: quay.io/opencloudio/
  pullPolicy: IfNotPresent
  clusterIssuer: cs-ca-clusterissuer
  output:
    splunk:
      host: master
      port: 8088
      token: abc-123
    hostAliases:
    - hostIP: 9.12.34.56
      hostnames:
      - test.fyre.ibm.com
