apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: commonaudits.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: CommonAudit
    listKind: CommonAuditList
    plural: commonaudits
    singular: commonaudit
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CommonAudit is the Schema for the commonaudits API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CommonAuditSpec defines the desired state of CommonAudit
          properties:
            clusterIssuer:
              type: string
            enabled:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
            imageRegistry:
              type: string
            output:
              description: CommonAuditSpecOutput defines the configurations
                for forwarding audit logs to Splunk or QRadar
              properties:
                hostAliases:
                  items:
                    description: CommonAuditSpecHostAliases defines the host
                      alias for an SIEM
                    properties:
                      hostIP:
                        type: string
                      hostnames:
                        items:
                          type: string
                        type: array
                    required:
                    - hostIP
                    - hostnames
                    type: object
                  type: array
                qradar:
                  description: CommonAuditSpecQRadar defines the configurations
                    for forwarding audit logs to QRadar
                  properties:
                    host:
                      type: string
                    hostname:
                      type: string
                    port:
                      type: integer
                  required:
                  - host
                  - hostname
                  - port
                  type: object
                splunk:
                  description: CommonAuditSpecSplunk defines the configurations
                    for forwarding audit logs to Splunk
                  properties:
                    host:
                      type: string
                    port:
                      type: integer
                    token:
                      type: string
                  required:
                  - host
                  - port
                  - token
                  type: object
              type: object
            pullPolicy:
              type: string
            replicas:
              type: integer
            resources:
              description: CommonAuditSpecResources defines the resources for
                the fluentd deployment
              properties:
                limits:
                  description: CommonAuditSpecRequirements defines cpu and
                    memory
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
                requests:
                  description: CommonAuditSpecRequirements defines cpu and
                    memory
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
              type: object
          type: object
        status:
          description: CommonAuditStatus defines the observed state of CommonAudit
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
