apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: auditloggings.operator.ibm.com
  labels:
    app.kubernetes.io/instance: common-audit-logging
    app.kubernetes.io/managed-by: ibm-auditlogging-operator
    app.kubernetes.io/name: common-audit-logging
spec:
  group: operator.ibm.com
  names:
    kind: AuditLogging
    listKind: AuditLoggingList
    plural: auditloggings
    singular: auditlogging
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AuditLogging is the Schema for the auditloggings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AuditLoggingSpec defines the desired state of AuditLogging
          properties:
            fluentd:
              description: AuditLoggingSpecFluentd defines the desired state of Fluentd
              properties:
                clusterIssuer:
                  type: string
                enabled:
                  type: boolean
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                journalPath:
                  type: string
                pullPolicy:
                  type: string
              type: object
            policyController:
              description: AuditLoggingSpecPolicyController defines the policy controller
                configuration in the the audit logging spec
              properties:
                frequency:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                pullPolicy:
                  type: string
                verbosity:
                  type: string
              type: object
          type: object
        status:
          description: AuditLoggingStatus defines the observed state of AuditLogging
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
