apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: commonaudits.operator.ibm.com
  labels:
      app.kubernetes.io/instance: common-audit-logging
      app.kubernetes.io/managed-by: ibm-auditlogging-operator
      app.kubernetes.io/name: common-audit-logging
spec:
  group: operator.ibm.com
  names:
    kind: CommonAudit
    listKind: CommonAuditList
    plural: commonaudits
    singular: commonaudit
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CommonAudit is the Schema for the commonaudits API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CommonAuditSpec defines the desired state of CommonAudit
          properties:
            clusterIssuer:
              type: string
            enabled:
              type: boolean
            fluentd:
              description: CommonAuditSpecFluentd defines the desired state of Fluentd
              properties:
                imageRegistry:
                  type: string
                pullPolicy:
                  type: string
                replicas:
                  type: integer
                resources:
                  description: CommonAuditSpecResources defines the resources for
                    the fluentd deployment
                  properties:
                    limits:
                      description: CommonAuditSpecRequirements defines cpu and memory
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      required:
                      - cpu
                      - memory
                      type: object
                    requests:
                      description: CommonAuditSpecRequirements defines cpu and memory
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      required:
                      - cpu
                      - memory
                      type: object
                  required:
                  - limits
                  - requests
                  type: object
              type: object
            outputs:
              description: CommonAuditSpecOutputs defines the configurations for forwarding
                audit logs to Splunk or Syslog
              properties:
                hostAliases:
                  items:
                    description: CommonAuditSpecHostAliases defines the host alias
                      for an SIEM
                    properties:
                      hostIP:
                        type: string
                      hostnames:
                        items:
                          type: string
                        type: array
                    required:
                    - hostIP
                    - hostnames
                    type: object
                  type: array
                splunk:
                  description: CommonAuditSpecSplunk defines the configurations for
                    forwarding audit logs to Splunk
                  properties:
                    host:
                      type: string
                    port:
                      type: integer
                    protocol:
                      description: 'This is the protocol to use for calling the HEC
                        API. Valid values are: "https" or "http"'
                      enum:
                      - https
                      - http
                      type: string
                    token:
                      type: string
                  required:
                  - host
                  - port
                  - protocol
                  - token
                  type: object
                syslog:
                  description: CommonAuditSpecSyslog defines the configurations for
                    forwarding audit logs to a syslog SIEM
                  properties:
                    host:
                      type: string
                    hostname:
                      type: string
                    port:
                      type: integer
                    tls:
                      type: boolean
                  required:
                  - host
                  - hostname
                  - port
                  - tls
                  type: object
              type: object
          type: object
        status:
          description: CommonAuditStatus defines the observed state of CommonAudit
          properties:
            nodes:
              description: The list of pod names for fluentd
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
