kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-auditlogging-operator
subjects:
- kind: ServiceAccount
  name: ibm-auditlogging-operator
  namespace: ibmcs-auditlogging
roleRef:
  kind: ClusterRole
  name: ibm-auditlogging-operator
  apiGroup: rbac.authorization.k8s.io
