apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-auditlogging-operator
  labels:
    app.kubernetes.io/instance: common-audit-logging
    app.kubernetes.io/managed-by: ibm-auditlogging-operator
    app.kubernetes.io/name: common-audit-logging
