apiVersion: audit.policies.ibm.com/v1alpha1
kind: AuditPolicy
metadata:
  name: audit-log-policy
spec:
  clusterAuditPolicy:
    auditPolicyRules:
      "platform-identity-manager": validate
  namespaceSelector:
    include:
      - ibm-common-services
  remediationAction: enforce # enforce or inform
